//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfFourRowServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveGame
    {
        public int GameId { get; set; }
        public string UserNameOne { get; set; }
        public string UserNameTwo { get; set; }
        public System.DateTime StartingDateTime { get; set; }
    }
}
