//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfFourRowServiceLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FourInRowDB_Context : DbContext
    {
        public FourInRowDB_Context()
            : base("name=FourInRowDB_Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HistoryGame> HistoryGames { get; set; }
        public virtual DbSet<LiveGame> LiveGames { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
